version: '3.8'

services:
  whatsapp-otp-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Server Configuration
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-5000}
      - DEBUG=${DEBUG:-False}
      
      # Basic Application API Configuration
      - BASIC_APPLICATION_API_URL=${BASIC_APPLICATION_API_URL}
      - BASIC_APPLICATION_USER_ID=${BASIC_APPLICATION_USER_ID}
      - BASIC_APPLICATION_API_KEY=${BASIC_APPLICATION_API_KEY}
      
      # Gupshup WhatsApp API Configuration
      - GUPSHUP_API_KEY=${GUPSHUP_API_KEY}
      - GUPSHUP_SOURCE=${GUPSHUP_SOURCE}
      - GUPSHUP_API_URL=${GUPSHUP_API_URL:-https://api.gupshup.io/wa/api/v1/msg}
      
      # Gupshup WhatsApp Templates
      - GUPSHUP_WHATSAPP_OTP_TEMPLATE_ID=${GUPSHUP_WHATSAPP_OTP_TEMPLATE_ID}
      - GUPSHUP_WHATSAPP_OTP_SRC_NAME=${GUPSHUP_WHATSAPP_OTP_SRC_NAME:-HomiAi}
      - GUPSHUP_LEAD_CREATION_TEMPLATE_ID=${GUPSHUP_LEAD_CREATION_TEMPLATE_ID}
      - GUPSHUP_LEAD_CREATION_SRC_NAME=${GUPSHUP_LEAD_CREATION_SRC_NAME}
      - GUPSHUP_LEAD_STATUS_TEMPLATE_ID=${GUPSHUP_LEAD_STATUS_TEMPLATE_ID}
      - GUPSHUP_LEAD_STATUS_SRC_NAME=${GUPSHUP_LEAD_STATUS_SRC_NAME}
      
      # Supabase Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      
      # OTP Configuration
      - OTP_EXPIRY_MINUTES=${OTP_EXPIRY_MINUTES:-3}
      
      # Production settings
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    restart: always
    volumes:
      - ./logs:/app/logs
    networks:
      - otp-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp

networks:
  otp-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: otp-bridge 